### ISSUE TITLE
Chinese toons failing to load

### ISSUE THREAD

**Issue by timwoj** [cheald/shadowcraft-ui#46]
Started GET "/cn/%e8%8a%ac%e9%87%8c%e6%96%af/%e7%a0%b4%e7%a2%8e%e7%9a%84%e7%8d%a0%e7%89%99" for 220.
181.108.186 at Wed Nov 26 00:07:10 -0500 2014
  Processing by CharactersController#show as */*
  Parameters: {"region"=>"cn", "name"=>"破碎的獠牙", "realm"=>"芬里斯"}
Completed 500 Internal Server Error in 443ms
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_request.text.erb (0.4ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_title.text.erb (0.2ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_session.text.erb (0.4ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_title.text.erb (0.0ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_environment.text.erb (58.3ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_title.text.erb (0.2ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_backtrace.text.erb (0.6ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/_title.text.erb (0.1ms)
Rendered vendor/bundle/ruby/1.8/bundler/gems/exception_notification-192a49a02d63/lib/exception_notif
ier/views/exception_notifier/exception_notification.text.erb (65.6ms)

Sent mail to cheald+shadowcraft@gmail.com, indzlord+shadowcraft@gmail.com (165ms)

Curl::Err::HostResolutionError (Curl::Err::HostResolutionError):
  lib/wow_armory/document.rb:61:in `fetch'
  lib/wow_armory/character.rb:62:in `initialize'
  app/models/character.rb:45:in `new'
  app/models/character.rb:45:in `update_from_armory!'
  app/models/character.rb:170:in `get!'
  app/controllers/characters_controller.rb:42:in `show'

**Comment by timwoj** [comment]
Blizzard fixed the Chinese version of the armory again, and this is now resolved.  Shadowcraft should be able to load Chinese toons again.
